# Generated by Django 3.2.9 on 2021-12-30 06:50

import Shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_mainpageproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSSlug', models.CharField(max_length=150)),
                ('NNName', models.CharField(max_length=150)),
                ('PPProduct_image', models.ImageField(upload_to=Shop.models.get_file_path)),
                ('DDDescription', models.TextField(max_length=500)),
                ('OOOrignal_price', models.FloatField()),
                ('SSSelling_price', models.FloatField()),
                ('SSStatus', models.BooleanField(default=False, help_text='0=default, 1=hidden')),
            ],
        ),
    ]
