# Generated by Django 3.2.9 on 2022-01-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20220109_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='DDDescription',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='NNName',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='OOOrignal_price',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='SSSelling_price',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='SSSlug',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='SSStatus',
        ),
    ]
