# Generated by Django 3.2.9 on 2022-01-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_auto_20220111_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='PPProduct_image',
            new_name='PPPProduct_image',
        ),
    ]
