# Generated by Django 3.2.9 on 2022-01-11 15:41

import Shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_rename_ppproduct_image_banner_pppproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PPPProduct_image', models.ImageField(upload_to=Shop.models.get_file_path)),
                ('NNNName', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='banner',
        ),
    ]
