# Generated by Django 3.2.9 on 2022-01-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20220111_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
