# Generated by Django 3.2.9 on 2022-01-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_rename_creared_at_cart_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
