# Generated by Django 3.2.9 on 2022-01-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_art'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='product',
            new_name='products',
        ),
    ]
