# Generated by Django 3.2.9 on 2022-01-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_rename_products_art_productd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='productd',
            new_name='product',
        ),
    ]
