# Generated by Django 3.2.9 on 2022-01-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_auto_20220117_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='orde',
        ),
    ]
